# Site settings
title: 像少年啦飞驰
email: your-email@domain.com
description: "记录思绪的点点滴滴"
baseurl: ""
url: "http://yourdomain.com"
github_username:  songxincun

# Build settings
markdown: kramdown
kramdown:
    input: GFM
highlight: rouge

redcarpet:
  extensions:
    - tables
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - disable_indented_code_blocks
    - underline
    - space_after_headers
    - superscript
    - footnotes

permalink: /blog/:year/:month/:day/:title
